### ISSUE TITLE
Add this repo to HACS

### ISSUE THREAD

**Issue by kevincaradant** [divanikus/braviatv_remote#1]
Hi :)

Do you think it's posible that you add it HACS ? :)

Thank you

**Comment by kevincaradant** [comment]
Oh I thought it was also the remote. Sorry it's just a script bash, so not really necessary to include it in HACS

**Comment by divanikus** [comment]
The official Bravia integration now contains almost whole functions of this module, so I myself moved to the official integration.

**Comment by kevincaradant** [comment]
Is it possible to have a remote ? I think I miss something in this case :)

**Comment by divanikus** [comment]
I don't quite seem to understand what you mean by remote?

**Comment by kevincaradant** [comment]
Maybe I didn't understand what your repository do. But it was for the TV remote isn't it ? 

In the aim to have something like that ? 

![image](https://user-images.githubusercontent.com/6093175/105421201-0536b380-5c42-11eb-82d4-d4635b207081.png)

At the moment I have just that:
![image](https://user-images.githubusercontent.com/6093175/105421251-197ab080-5c42-11eb-9383-d7e38c1f3c8e.png)

I saw your repo from here:
https://community.home-assistant.io/t/sony-bravia-android-tv/79682/23

**Comment by divanikus** [comment]
It was made to simulate keypresses from TV Remote through `remote.send_command` service. So, yes, it's purpose is to use it as a virtual remote. It do not contain a card, you have to create buttons for each action yourself.

But if you wish just to switch to a channel or start an app on your TV, official Bravia integration can do that.

**Comment by kevincaradant** [comment]
Yes I would like to start an app like twitch or YouTube. I only see tv channels on the official app. I will check it again :)

Thanks
